# Dependencies
markdown: kramdown
gems: [jekyll-paginate]

# Setup
timezone: America/Sao_Paulo
permalink: /:categories/:title.html/

author:
  name: 'Diego de Souza Mendes'
  email: 'diegosouza.br@gmail.com'

title: 'diegosouza@blog'
description: '# tail -f ideias pensamentos experiências >> blog'
url: https://diegosouza.github.io
paginate: 5
